# This file was generated by GoReleaser. DO NOT EDIT.
cask "noxmem" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "1805cec832405464a1801decfdf88d533f7c583f733b6943280b40e59bf102c9"
      url "https://github.com/crumbyte/noxmem/releases/download/v#{version}/noxmem-v#{version}-Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ed207b2e4d5c5dde73c8ff2019b6ffd8d804eddb3bbe54b9863d3a64e0e63e2"
      url "https://github.com/crumbyte/noxmem/releases/download/v#{version}/noxmem-v#{version}-Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c9af17ddaa5686d4e0b1d89dd997ea1f68022077ac4cf83bf4044eb608be98f"
      url "https://github.com/crumbyte/noxmem/releases/download/v#{version}/noxmem-v#{version}-Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aaa3176de605bc40d027ce3868dee162d87579c29ad0df44e0c9ea4e722ad583"
      url "https://github.com/crumbyte/noxmem/releases/download/v#{version}/noxmem-v#{version}-Linux_x86_64.tar.gz"
    end
  end

  name "noxmem"
  desc "Terminal utility for live GoLang heap memory profiling."
  homepage "https://github.com/crumbyte/noxmem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noxmem"
  manpage "man/noxmem.1"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noxmem"]
    end
  end

  # No zap stanza required
end
